[package]
name = "cli"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true, features = ["derive"] }
sql = { workspace = true }
